### ISSUE TITLE
lto1 error when running create_env.sh

### ISSUE THREAD

**Issue by sean-lin-tw** [cksystemsgroup/scalloc-artifact#1]
I tried to build the tool with create_env.sh
When my compiler(g++-4.9.3) tried to build the SuperMalloc allocator, the following error message showed.
`lto1: fatal error: bytecode stream generated with LTO version 4.0 instead of the expected 3.0`
Can anyone help me deal with this problem?

**Comment by mlippautz** [comment]
Did you try building using Ubuntu 14.04 LTS? 

gcc 4.9.3. seems too new for 14.04. In case you upgraded your toolchain, you might have missed some libraries as the error basically tells you that linking failed due to generated code being different. 

In any case: The scripts are just wrappers, so you can try and build SuperMalloc on your own from https://github.com/kuszmaul/SuperMalloc. Once that works for your setup, you should be able to build the artifact.

**Comment by sean-lin-tw** [comment]
Same issue occurred when I tried to build SuperMalloc alone.
I've reported the issue on their repository as well.
I'll also try to build this tool on a VM with Ubuntu 14.04 image to see if that works.
Thanks!

**Comment by sean-lin-tw** [comment]
I tried building gcc-4.8.5 on Ubuntu 15.10 and create_env.sh could be successfully be executed

**Comment by ckirsch** [comment]
Nice to hear that. Many thanks for using scalloc!
